baseurl = "https://shipovdenis.ru"
languageCode = "ru"
title = "КРАСОТА | ЗДОРОВЬЕ"
theme = "HUCORE"
copyright = "&copy; 2017 | Денис Шипов"
disqusShortname = "shipovdenis"
googleAnalytics = "trackingcode"

enableRobotsTXT = true

publishDir = "docs"

[taxonomies]
tag = "tags"
category = "categories"

[params]
description = "Блог о красоте и здоровье"
keywords = ["красота", "здоровье"]
author = "Денис Шипов"
sharingicons = true

[[params.social]]
url = "https://vk.com/myhealthtips"
fa_icon = "fa-vk"

[[params.social]]
url = "/index.xml"
fa_icon = "fa-rss"
